WINDOW_SIZE = (800, 200)

# MainWindow
BACKGROUND_COLOR = "#11111b"
FORGROUND_COLOR = "#cdd6f4"

# PasswordWindow
PASSWORD_INPUT_BACKGROUND_COLOR = "#565f89"
PASSWORD_INPUT_FORGROUND_COLOR = "#11111b"
PASSWORD_INPUT_BORDER_COLOR = "#a6e3a1"

ENTER_BUTTON_BACKGROUND_COLOR = "#89b4fa"
ENTER_BUTTON_FORGROUND_COLOR = "#11111b"
ENTER_BUTTON_HOVER_BACKGROUND_COLOR = "#8be9fd"

WIDGETS_RADIUS = "10px";


